name: Verilator Testbench

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: verilator/verilator:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Compile Verilog code
        run: verilator -Wall -cc tb.v --exe testbench.cpp
      - name: Build testbench
        run: make -C obj_dir/ -j -f Vtb.mk Vtb
      - name: Run testbench
        run: obj_dir/Vtb
